### ISSUE TITLE
eql specializers / `Literal` types

### ISSUE THREAD

**Issue by remexre** [coady/multimethod#48] opened 2021-08-09 22:49 UTC
If one tries to specialize on an argument with a `Literal[_]` type, they get `TypeError: typing.Literal cannot be used with issubclass()`. It'd be nice to have support for this; I suspect patching `issubclass` to add the following rules would work:

- `Literal[x] <: Literal[x]`
- `Literal[x] <: type(x)`

**Comment by coady** [comment] 2021-08-10 00:39
Duplicate of #44. As of 5f4bf2a, literals are partially supported. The params will participate as a subclass check (but not actually check the literal values).

**Closed** 2021-08-20 01:36 UTC
