### ISSUE TITLE
Dispatch on empty list does not work

### ISSUE THREAD

**Issue by adam-urbanczyk** [coady/multimethod#52] opened 2021-09-08 06:57 UTC
The following does result in a DispatchError:
```python
from multimethod import multimethod
from typing import List

class Dummy:
    
    @multimethod
    def dummy(self, a: float,b : List[float]):
        
        pass

Dummy().dummy(1.0, [1.0])
Dummy().dummy(1.0, [])
```
Is it intended?

**Comment by adam-urbanczyk** [comment] 2021-09-08 20:45
BTW: If you are OK with solving this (by e.g. adding another key to the dispatch dict; first come first served in the case of ambiguities) it'd be great to have it before #50 ...

**Comment by coady** [comment] 2021-09-09 01:12
This has come up before: #31.

The problem is handling ambiguity. I think that `[]` should match `List[bool]` over `List[int]`, but also suspect that that would be surprising and perceived as a bug to users.

**Comment by adam-urbanczyk** [comment] 2021-09-12 16:17
Thanks for the reference. I'm not sure what you mean with matching bool over int. I was just hoping for a solution that matches any list that was specified in the signature. In the case of ambiguities matching first (or last) defined would be perfectly fine.

Otherwise, do you have any suggestions regarding working around this issue?

**Comment by coady** [comment] 2021-09-12 18:35
Ok, I'm willing to try it, as long as it's marked as provisional. Maybe there won't be any issues filed over ambiguous dispatch. Also, `[]` can be used be as a literal now.

**Closed** 2021-09-12 18:47 UTC

**Comment by adam-urbanczyk** [comment] 2021-09-15 06:07
Great, current solution works perfectly for my use case.
